# Generated by Django 5.0.4 on 2024-06-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_remove_receta_medico_receta_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='AsistenteMedico',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
    ]
