# Generated by Django 5.0.4 on 2024-06-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo_qr', models.ImageField(blank=True, upload_to='codigos_qr/')),
            ],
        ),
    ]
