# Generated by Django 5.0.4 on 2024-06-04 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('obra_social', models.CharField(max_length=100)),
                ('numero_afiliado', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=10)),
                ('ultima_medicacion', models.CharField(max_length=255)),
                ('dosis_diaria', models.CharField(max_length=255)),
                ('app', models.TextField(verbose_name='Antecedentes Patológicos Personales')),
                ('aqx', models.TextField(verbose_name='Antecedentes Quirúrgicos')),
                ('complicaciones', models.TextField(verbose_name='Complicaciones (agudas y/o crónicas)')),
                ('actividad_fisica', models.TextField()),
                ('act_laboral', models.TextField(verbose_name='Actividad Laboral')),
                ('clinica', models.TextField()),
                ('amg', models.TextField(verbose_name='Automonitoreo Glucémico')),
                ('laboratorio', models.TextField()),
                ('interconsultas', models.TextField()),
                ('conducta', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
