# Generated by Django 5.0.4 on 2024-06-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('obra_social', models.CharField(max_length=100)),
                ('numero_afiliado', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('medicacion', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
