# Generated by Django 5.0.4 on 2024-06-06 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20)),
                ('obra_social', models.CharField(max_length=100)),
                ('numero_afiliado', models.CharField(max_length=100)),
                ('medicacion', models.CharField(max_length=200)),
                ('droga', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('presentacion', models.CharField(max_length=100)),
                ('marca_recomendada', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_unidades', models.IntegerField()),
                ('firma_medica', models.CharField(max_length=200)),
                ('qr_codigo_barras', models.CharField(max_length=100, unique=True)),
                ('fecha_ultimo_laboratorio', models.DateField()),
                ('proxima_fecha_empadronamiento', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='users.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='pacientes.paciente')),
            ],
        ),
    ]
