# Generated by Django 5.0.4 on 2024-06-27 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='medico',
        ),
        migrations.AddField(
            model_name='receta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='algun_nombre_relacionado', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
