# Generated by Django 5.0.4 on 2024-07-01 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_remove_receta_medico_receta_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='numero_afiliado',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='obra_social',
        ),
        migrations.AlterField(
            model_name='receta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL),
        ),
    ]
