# Generated by Django 3.2.25 on 2024-07-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_remove_receta_dni_remove_receta_nombre_completo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='dosis',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='receta',
            name='droga',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='receta',
            name='marca_recomendada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='presentacion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='receta',
            name='qr_codigo_barras',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
