# Generated by Django 3.2.25 on 2024-07-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0004_auto_20240711_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='cantidad_unidades',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='droga',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='marca_recomendada',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='medicacion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='qr_codigo_barras',
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droga', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=200)),
                ('presentacion', models.CharField(max_length=200)),
                ('marca_recomendada', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad_unidades', models.IntegerField()),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicacion', to='recetas.receta')),
            ],
        ),
    ]
