# Generated by Django 3.2.25 on 2024-08-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_auto_20240717_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicacion',
            name='cantidad_unidades',
        ),
        migrations.RemoveField(
            model_name='medicacion',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='medicacion',
            name='receta',
        ),
        migrations.CreateModel(
            name='RecetaMedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=200)),
                ('cantidad_unidades', models.IntegerField()),
                ('medicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.medicacion')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='medicacion',
            field=models.ManyToManyField(through='recetas.RecetaMedicacion', to='recetas.Medicacion'),
        ),
    ]
