# Generated by Django 5.0.4 on 2024-07-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0005_auto_20240717_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
