# Generated by Django 3.2.25 on 2024-08-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0006_auto_20240821_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='cantidad_unidades',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receta',
            name='dosis',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.RemoveField(
            model_name='receta',
            name='medicacion',
        ),
        migrations.AddField(
            model_name='receta',
            name='medicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='recetas.medicacion'),
        ),
        migrations.DeleteModel(
            name='RecetaMedicacion',
        ),
    ]
