# Generated by Django 3.2.25 on 2024-09-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0008_auto_20240822_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='custom_id',
            field=models.CharField(blank=True, default='romanmas10', editable=False, max_length=20),
        ),
    ]
