# Generated by Django 3.2.25 on 2024-09-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0010_rename_custom_id_receta_codigo_de_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='codigo_de_receta',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
