# Generated by Django 5.0.4 on 2024-06-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20)),
                ('obra_social', models.CharField(max_length=100)),
                ('numero_afiliado', models.CharField(max_length=100)),
                ('pedido', models.TextField()),
                ('fecha', models.DateField()),
                ('firma', models.CharField(max_length=200)),
                ('codigo_identificacion', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
