# Generated by Django 3.2.25 on 2024-08-24 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_provincia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos_laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidolaboratorio',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='pedidolaboratorio',
            name='nombre_apellido',
        ),
        migrations.RemoveField(
            model_name='pedidolaboratorio',
            name='numero_afiliado',
        ),
        migrations.RemoveField(
            model_name='pedidolaboratorio',
            name='obra_social',
        ),
        migrations.AddField(
            model_name='pedidolaboratorio',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_laboratorio', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='pedidolaboratorio',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_firmados', to=settings.AUTH_USER_MODEL),
        ),
    ]
