# Generated by Django 3.2.25 on 2024-08-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_provincia'),
        ('pedidos_laboratorio', '0002_auto_20240824_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidolaboratorio',
            name='firma',
        ),
        migrations.AddField(
            model_name='pedidolaboratorio',
            name='firma_medica',
            field=models.CharField(default='Sin firma', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedidolaboratorio',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_laboratorio', to='pacientes.paciente'),
        ),
    ]
